apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure apps (cert-manager, ingress, etc.) deployed to all spokes

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
